### ISSUE TITLE
Anchor Doesn't Support Have Good Support For User Defined Types

### ISSUE THREAD

**Issue by bonedaddy** [coral-xyz/anchor#192]
# Overview

Anchor doesnt have good support for user defined types in instruction handlers. Ive encountered this issue with float types, as well as enum types.

# Example

```
Error: User defined types not provided
    at Function.fieldLayout (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:344:19)
    at /media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:366:28
    at Array.map (<anonymous>)
    at Function.typeDefLayout (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:365:48)
    at /media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:149:34
    at Array.map (<anonymous>)
    at new AccountsCoder (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:148:54)
    at new Coder (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/coder.ts:61:21)
    at new Program (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/program.ts:68:19)
    at /media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/workspace.ts:43:28
    at Array.reduce (<anonymous>)
    at Object.get (/media/solidity/DATA1/Code/noop/protocol/node_modules/@project-serum/anchor/src/workspace.ts:39:10)
    at Suite.<anonymous> (/media/solidity/DATA1/Code/noop/protocol/tests/protocol.spec.ts:13:41)
    at Object.create (/home/solidity/.npm_modules/lib/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/solidity/.npm_modules/lib/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/media/solidity/DATA1/Code/noop/protocol/tests/protocol.spec.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (/home/solidity/.npm_modules/lib/node_modules/ts-mocha/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/home/solidity/.npm_modules/lib/node_modules/ts-mocha/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (/home/solidity/.npm_modules/lib/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/solidity/.npm_modules/lib/node_modules/mocha/lib/esm-utils.js:55:34)
    at singleRun (/home/solidity/.npm_modules/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
```

**Comment by AuroraLantean** [comment]
How to define my own array of structs to be saved into a program derived account? 
I got this error: User defined types not provided!

```
#[account]
#[derive(Default)]
pub struct UserData {
  pub authority: Pubkey,
  pub pool_array: [Pool; 20],
  pub __nonce: u8,
}
#[account]
#[derive(Default)]
#[derive(Copy)]//index as pid
pub struct Pool {
  pub shares: u64,
  pub reward_debt: u64,
}
```

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
