### ISSUE TITLE
anchor test for basic examples in the tutorials fails with anchor 0.24.2 

### ISSUE THREAD

**Issue by chiumichael** [coral-xyz/anchor#1975]
Hi there. 

I'm going through the tutorials and I can't seem to run the tests (using `anchor test`) for the tutorials. `anchor build` and `anchor deploy` works though.  

I'm using `v1.10.25` for the solana-cli and `v0.24.2` for anchor-cli. 

```sh
Found a 'test' script in the Anchor.toml. Running it as a test suite!

Running test suite: "/Users/chiu/code/anchor/examples/tutorial/basic-1/Anchor.toml"

yarn run v1.22.18
$ /Users/chiu/code/anchor/examples/tutorial/node_modules/.bin/mocha -t 1000000 tests/

Error: Cannot find module '/Users/chiu/code/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:354:19)
    at Module._findPath (node:internal/modules/cjs/loader:567:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/chiu/code/anchor/examples/tutorial/basic-1/tests/basic-1.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async formattedImport (/Users/chiu/code/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async exports.requireOrImport (/Users/chiu/code/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async exports.loadFilesAsync (/Users/chiu/code/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (/Users/chiu/code/anchor/examples/tutorial/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/Users/chiu/code/anchor/examples/tutorial/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looking into the error, I seem to missing the `.../@project-serum/anchor/dist/` folder completely. I've run the `yarn install` command before this so I'm not sure why this is happening. 

Any help would be much appreciated.

**Comment by DAIXK** [comment]
same

**Comment by chiumichael** [comment]
Okay, figured this out. `anchor/ts` needs to be built with `yarn`. Then, the `node_modules' folder needs to be removed. Finally, after `yarn install`, as suggested by the documentation , `anchor test` should work.
