### ISSUE TITLE
Mint spl-token by using Anchor, `Error processing Instruction 0: custom program error: 0xbc0`

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2048]
I have coded to mint new spl-token.
in lib.rs
```js

    pub fn initialize(ctx: Context<Initialize>, _global_bump: u8) -> Result<()> {
        let global_authority = &mut ctx.accounts.global_authority;
        global_authority.super_admin = ctx.accounts.admin.key();
        Ok(())
    }


#[derive(Accounts)]
#[instruction(bump: u8)]
pub struct Initialize<'info> {
    #[account(mut)]
    pub admin: Signer<'info>,
    #[account(
        init,
        seeds = [GLOBAL_AUTHORITY_SEED.as_ref()],
        bump,
        space = 8 + 40,
        payer = admin
    )]
    pub global_authority: Account<'info, GlobalPool>,

    #[account(
        init, 
        payer = admin, 
        mint::decimals = 9, 
        mint::authority = global_authority, 
        mint::freeze_authority = global_authority
    )]
    pub reward_token: Account<'info, Mint>,

    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>
}
```
and in typescript code:
```js
const [globalAuthority, bump] = await PublicKey.findProgramAddress(
        [Buffer.from(GLOBAL_AUTHORITY_SEED)],
        STAKING_PROGRAM_ID,
    );
    let key = Keypair.generate();

  //   const rewardToken = await createMint(
  //      solConnection,
  //      key,
  //      globalAuthority,
  //      globalAuthority,
  //      9 // We are using 9 to match the CLI decimal default exactly
  //    );

  //    console.log(rewardToken.toBase58());
    let tx = new Transaction();
    console.log('==>Initializing Program');

    tx.add(program.instruction.initialize(
        bump, {
        accounts: {
            admin: userAddress,
            globalAuthority,
            rewardToken: key.publicKey,
            tokenProgram: TOKEN_PROGRAM_ID,
            systemProgram: SystemProgram.programId,
            rent: SYSVAR_RENT_PUBKEY,
        },
        instructions: [],
        signers: [],
    }));

```

and I got this error:
```ps
/home/ubuntu/apollo/test_mint/test/node_modules/@solana/web3.js/src/connection.ts:4464
      throw new SendTransactionError(
            ^
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc0
    at Connection.sendEncodedTransaction (/home/ubuntu/apollo/test_mint/test/node_modules/@solana/web3.js/src/connection.ts:4464:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/home/ubuntu/apollo/test_mint/test/node_modules/@solana/web3.js/src/connection.ts:4423:20)
    at Connection.sendTransaction (/home/ubuntu/apollo/test_mint/test/node_modules/@solana/web3.js/src/connection.ts:4411:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by acheroncrypto** [comment]
Previous comment explained the issue perfectly.
