### ISSUE TITLE
[Error: Method does not support views] using <transaction>.view()

### ISSUE THREAD

**Issue by ElectronicaGitHub** [coral-xyz/anchor#2089]
Following the example from https://www.anchor-lang.com/docs/cross-program-invocations, I've tried to return the values, which is `Reading return data in the clients` about.

Invoked method returns values which is a struct decorated with (de)serializers

When I'm calling .rpc() - all good, when changing it into .view() - I get the error
```
Error: Method does not support views
      at MethodsBuilder.view (node_modules/@project-serum/anchor/src/program/namespace/methods.ts:147:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I've tried to investigate it, but at the glance looks like bug, hope I'm wrong, but then tutorial should also reveal the details.

Calling method
```
...
pub fn pull_strings(ctx: Context<PullStringsContext>, data: u64) -> Result<PullStringResult> {
        let ctx = ctx.accounts.set_data_ctx();
        let result = puppet::cpi::set_data(ctx, data)?;

        Ok(
            PullStringResult { value: result.get() }
        )
    }
...
```

Result struct
```
#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct PullStringResult {
    value: u64
}
```

Code from test
```
const result = await puppetMasterProgram.methods
      .pullStrings(new anchor.BN(VALUE))
      .accounts({
        puppetProgram: puppetProgram.programId,
        puppet: puppetKeyPair.publicKey,
        authority: authorityKeyPair.publicKey
      })
      .signers([authorityKeyPair])
      // .rpc(); -> works fine
      .view(); -> gives error
```

**Comment by ElectronicaGitHub** [comment]
`cpi-returns` example from repo gave understanding, thank you guys!! 

You're doing really great framework in such new area!
