### ISSUE TITLE
 Error: Invalid arguments: myAccount not provided.

### ISSUE THREAD

**Issue by karan-ksrk** [coral-xyz/anchor#2095]
```
 it("Creates and initializes an account in a single atomic transaction (simplified)", async () => {
    // #region code-simplified
    // The program to execute.
    const program = anchor.workspace.Basic1;

    // The Account to create.
    const myAccount = anchor.web3.Keypair.generate();

    // Create the new account and initialize it with the program.
    // #region code-simplified
    await program.rpc.initialize({
      accounts: {
        myAccount: myAccount.publicKey,
        user: provider.wallet.publicKey,
        systemProgram: SystemProgram.programId,
      },
      signers: [myAccount],
    });
    // #endregion code-simplified

    // Fetch the newly created account from the cluster.
    const account = await program.account.myAccount.fetch(myAccount.publicKey);

    // Check it's state was initialized.
    assert.equal(account.data, 0);

    // Store the account for the next test.
    _myAccount = myAccount;
  });
```
while testing, Even I pass the all argument correct inside program.rpc.initialize(), I am getting invalid argument error

 ```
basic-1
    1) Creates and initializes an account in a single atomic transaction (simplified)
    2) Updates a previously created account


  0 passing (31ms)
  2 failing

  1) basic-1
       Creates and initializes an account in a single atomic transaction (simplified):
     Error: Invalid arguments: myAccount not provided.
      at /home/ksrk/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/common.js:39:23
      at Array.forEach (<anonymous>)
      at validateAccounts (/home/ksrk/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/common.js:33:16)
      at ix (/home/ksrk/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/namespace/instruction.js:38:46)
      at txFn (/home/ksrk/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/namespace/transaction.js:16:20)
      at Object.rpc [as initialize] (/home/ksrk/anchor/examples/tutorial/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:9:24)
      at Context.<anonymous> (tests/basic-1.js:24:23)
      at processImmediate (node:internal/timers:466:21)

  2) basic-1
       Updates a previously created account:
     TypeError: Cannot read properties of null (reading 'publicKey')
      at Context.<anonymous> (tests/basic-1.js:55:30)
      at processImmediate (node:internal/timers:466:21)



error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by karan-ksrk** [comment]
found the solution

**Comment by jovi-isorena** [comment]
can you please tell the solution? I'm having a similar problem in my tests

**Comment by Henry-E** [comment]
For debugging help it's better to try the anchor discord or https://solana.stackexchange.com/
