### ISSUE TITLE
Accountloader's load_init() error

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2312]
In my code I built the account structure as 
```rs
#[account(zero_copy)]
pub struct AuctionPool {
    pub seller: Pubkey,         // 32

    pub nft_mint: Pubkey,       // 32
    pub nft_creator: Pubkey,    // 32

    pub bidder: Pubkey,         // 32
    pub current_bid: u64,       // 8
    
    pub start_price: u64,       // 8
    pub end_time: u64,          // 8

    // 1: active, 2: canceled, 3: claimed
    pub status: u64,            // 8
    pub bump: u8,              // 1
}
```
and  in the lib.rs
```rs
 let mut auction = ctx.accounts.auction.load_init()?;
...
#[derive(Accounts)]
pub struct CreateAuction<'info> {
    // Main Auction PDA to store the data
    #[account(zero)]
    pub auction: AccountLoader<'info, AuctionPool>,
...
```
And in the script file
```ts
 let ix = SystemProgram.createAccountWithSeed({
        fromPubkey: userAddress,
        basePubkey: userAddress,
        seed: str,
        newAccountPubkey: auction,
        lamports: await solConnection.getMinimumBalanceForRentExemption(AUCTION_SIZE),
        space: AUCTION_SIZE,
        programId: AUCTION_PROGRAM_ID,
    });
  
...

    let tx = new Transaction();

    tx.add(ix);
    tx.add(program.instruction.createAuction(
        new anchor.BN(startPrice * HTO_TOKEN_DECIMAL), new anchor.BN(duration), {
        accounts: {
            auction,
            globalAuthority,
            auctionAta,
            owner: userAddress,
            ownerAta: userTokenAccount,
            mint,
            mintMetadata,
            ataProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
            tokenProgram: TOKEN_PROGRAM_ID,
            systemProgram: SystemProgram.programId,
            rentSysvar: SYSVAR_RENT_PUBKEY,
        },
        instructions: [],
        signers: [],
    }));
```

And I got this error:
```ps
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: Program failed to complete
    at Connection.sendEncodedTransaction (/home/ubuntu/apollo/Auction-Program/auction/node_modules/@solana/web3.js/src/connection.ts:4934:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.sendRawTransaction (/home/ubuntu/apollo/Auction-Program/auction/node_modules/@solana/web3.js/src/connection.ts:4893:20)
    at sendAndConfirmRawTransaction (/home/ubuntu/apollo/Auction-Program/auction/node_modules/@project-serum/anchor/src/provider.ts:288:21)
    at AnchorProvider.sendAndConfirm (/home/ubuntu/apollo/Auction-Program/auction/node_modules/@project-serum/anchor/src/provider.ts:148:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Henry-E** [comment]
Very well constructed preface but this query is probably more suited to https://solana.stackexchange.com/ unless there's a clear issue with anchor happening here?
