### ISSUE TITLE
Error Number: 101 InstructionFallbackNotFound on vite production build

### ISSUE THREAD

**Issue by viandwi24** [coral-xyz/anchor#2371]
I got an error as detailed below when I built it for production.
but when i do it in dev mode it runs normally.

is there something wrong with my vite settings?

my vite config:
```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import { fileURLToPath } from 'url'
import nodePolyfills from "rollup-plugin-node-polyfills"
import plinject from "@rollup/plugin-inject"

export default defineConfig({
  plugins: [react()],
  define: {
    global: '({})',
    'process.env': {
      NODE_DEBUG: 'TRUE',
    },
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      util: 'util',
      sys: 'util',
      events: 'rollup-plugin-node-polyfills/polyfills/events',
      stream: 'rollup-plugin-node-polyfills/polyfills/stream',
      process: 'rollup-plugin-node-polyfills/polyfills/process-es6',
      zlib: 'rollup-plugin-node-polyfills/polyfills/zlib',
      buffer: 'rollup-plugin-node-polyfills/polyfills/buffer-es6',
      assert: 'rollup-plugin-node-polyfills/polyfills/assert',
    },
  },
  build: {
    rollupOptions: {
      plugins: [
        nodePolyfills(),
        plinject({
          modules: {
            Buffer: ['buffer', 'Buffer'],
            Process: ['process', 'Process'],
          }
        })
      ],
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis'
      },
    }
  },
})

```

my error :
```
Ticket claim failed Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.
    at AnchorError.parse (index-72c23f95.js:349:1163)
    at translateError (index-72c23f95.js:349:2662)
    at MethodsBuilder._rpcFn (index-72c23f95.js:349:48579)
    at async BadgeMinter.claimFromTicket (index-72c23f95.js:349:78013)
    at async Nt (index-72c23f95.js:362:322)
```

transaction response rpc : 
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32002,
    "message": "Transaction simulation failed: Error processing Instruction 2: custom program error: 0x65",
    "data": {
      "accounts": null,
      "err": {
        "InstructionError": [
          2,
          {
            "Custom": 101
          }
        ]
      },
      "logs": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program 4oNsZ8Rwgkmkp5eDoZTpeJG6uNae7mLmZWpj8Tm7tjZy invoke [1]",
        "Program log: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.",
        "Program 4oNsZ8Rwgkmkp5eDoZTpeJG6uNae7mLmZWpj8Tm7tjZy consumed 5377 of 280000 compute units",
        "Program 4oNsZ8Rwgkmkp5eDoZTpeJG6uNae7mLmZWpj8Tm7tjZy failed: custom program error: 0x65"
      ],
      "returnData": null,
      "unitsConsumed": 0
    }
  },
  "id": "6ea93045-201c-440f-86b7-869b115d5b5f"
}
```

**Comment by Henry-E** [comment]
This is more a discord / stackoverflow kind of question. 

Fallback not found usually means the discriminator of the instruction you sent doesn't match any of the functions in your program. It's possible your IDL is out of date.

**Comment by viandwi24** [comment]
@Henry-E  I'm getting confused, I'm using the same idl. when in dev mode it works, but when in production mode it doesn't work and generates an error like this. but thanks for your answer.

**Comment by AlexanderTirik** [comment]
Try to remove `global` key from `define` in vite config, it will fix your problem. For some reason, the builder changes the data serialization functionality and this global key is the reason

**Comment by effeaucarre** [comment]
i also have the same error with vue & vite. very strange case because it worked, and it's not working anymore without having touched the code.

**Comment by viandwi24** [comment]
I don't know what this problem is, but recently I found everything working smoothly again after I changed my Vite config as follows
```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
import nodePolyfills from 'rollup-plugin-node-polyfills'
import { fileURLToPath, URL } from "url"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      stream: 'rollup-plugin-node-polyfills/polyfills/stream',
      events: 'rollup-plugin-node-polyfills/polyfills/events',
      assert: 'assert',
      crypto: 'crypto-browserify',
      util: 'util',
    },
  },
  define: {
    'process.env': process.env ?? {},
    "process.env.BROWSER": true,
  },
  esbuild: {
    target: "esnext",
  },
  build: {
    target: "esnext",
    rollupOptions: {
      plugins: [
        nodePolyfills({ crypto: true }),
      ],
    },
  },
  optimizeDeps: {
    include: ["@solana/web3.js", "buffer", "@metaplex-foundation/js"],
    esbuildOptions: {
      plugins: [
        NodeGlobalsPolyfillPlugin({ buffer: true }),
      ],
    }
  },
})
```

as @AlexanderTirik  said, it looks like this issue arose because there was a `global` in my `define` so tried removing it

**Comment by geoshak** [comment]
I was getting this same error while using "anchor run test" so it used a local running validator.

Once I reverted to using "anchor test" the issue went away.
