### ISSUE TITLE
anchor test for basic examples in the tutorials fails with anchor 0.26

### ISSUE THREAD

**Issue by mafux777** [coral-xyz/anchor#2403]
Hi there.

I'm going through the tutorials and I can't seem to run the tests (using anchor test) for the tutorials. anchor build and anchor deploy works though.

```
funkmeister380@MacBook-Pro-von-Matias ~ % solana --version
solana-cli 1.15.2 (src:dea65f48; feat:1211687720, client:SolanaLabs)
funkmeister380@MacBook-Pro-von-Matias ~ % anchor --version
anchor-cli 0.26.0

funkmeister380@MacBook-Pro-von-Matias basic-1 % anchor run test
yarn run v1.22.19
$ /Users/funkmeister380/anchor/examples/tutorial/node_modules/.bin/mocha -t 1000000 tests/

Error: Cannot find module '/Users/funkmeister380/anchor/examples/tutorial/node_modules/@coral-xyz/anchor/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:349:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/funkmeister380/anchor/examples/tutorial/basic-1/tests/basic-1.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/Users/funkmeister380/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/funkmeister380/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/Users/funkmeister380/anchor/examples/tutorial/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (/Users/funkmeister380/anchor/examples/tutorial/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/funkmeister380/anchor/examples/tutorial/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
```

I have looked at a related issue but unable to make it work. 
https://github.com/coral-xyz/anchor/issues/1975

**Comment by Henry-E** [comment]
don't use solana cli 1.15

**Comment by mafux777** [comment]
Turns out I was able to get this working by changing the version number from 0.26 to 0.25 in the package.json
I don't think the Solana client was the culprit
