### ISSUE TITLE
Large anchor event deserialization error

### ISSUE THREAD

**Issue by Rohitkk432** [coral-xyz/anchor#2607]
we have a transaction with multiple instructions with a large number of events in it 
the transaction is successful on [solscan](https://solscan.io/tx/5tiWCxqZ9g1pzzxPGJWJdwyoYcWt3jRASWXGo9admeU8QGaUTgaCKsVqYC45T6ya2avFfP35YfyDgvWAm7uVB1Mm?cluster=devnet).

but only one event is deserialized successfully.
and on the second event this error is logged. 

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 152. Received 160
    at new NodeError (node:internal/errors:399:5)
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt32LE (node:internal/buffer:222:5)
    at Buffer.readUIntLE (node:internal/buffer:180:17)
    at UInt.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/buffer-layout/lib/Layout.js:570:14)
    at Structure.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/buffer-layout/lib/Layout.js:1237:32)
    at WrappedLayout.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/@project-serum/borsh/dist/lib/index.js:64:41)
    at WrappedLayout.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/@project-serum/borsh/dist/lib/index.js:64:41)
    at Structure.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/buffer-layout/lib/Layout.js:1237:32)
    at BorshEventCoder.decode (/home/ubuntu/projects/defios-nodejs-api/node_modules/@project-serum/anchor/dist/cjs/coder/borsh/event.js:80:29) {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by acheroncrypto** [comment]
Could you share a reproducable example for this error?

**Comment by tanmaymunjal** [comment]
Yeah, taking a closer look at this, it seems to be an issue with log compression in RPC. Trying to migrate this to CPI events. Not an issue with Anchor, will prob ping him to close.
