### ISSUE TITLE
Method Builder: Account array does not get parsed

### ISSUE THREAD

**Issue by hernandp** [coral-xyz/anchor#2858]
I'm using Anchor to call Circle and Wormhole programs in Solana.  For example, the following works splendidly:

```
  const wallet = new Wallet(keypair)
  const provider = new AnchorProvider(connection, wallet, { commitment: 'finalized' })
  setProvider(provider)
  const tokenMessengerMinterProgram = new Program(TokenMessengerMinterIdl as Idl, TOKEN_MESSENGER_MINTER_PROGRAM_ID)
  const AVAX_DESTINATION_DOMAIN = 1

  const msgSendEventData = Keypair.generate();
  const tx = await tokenMessengerMinterProgram.methods.depositForBurn({
    // Transfer (burn) amount.
    amount: new BN(amount),

    // Circle Domain
    destinationDomain: AVAX_DESTINATION_DOMAIN,

    // Recipient of assets on target network.
    mintRecipient: new PublicKey(Buffer.from('0000000000000000000000001fb8B6743E8d4F8047cd9C216192D4cD897947a2', 'hex')),  // CCTP Dev Hub
  }
  ).accountsStrict({
    owner: keypair.publicKey,
    senderAuthorityPda: findProgramAddress('sender_authority', TOKEN_MESSENGER_MINTER_PROGRAM_ID).publicKey,
    burnTokenAccount: senderTokenAccount.address,
    messageTransmitter: findProgramAddress('message_transmitter', MESSAGE_TRANSMITTER_PROGRAM_ID).publicKey,
    tokenMessenger: findProgramAddress('token_messenger', TOKEN_MESSENGER_MINTER_PROGRAM_ID).publicKey,
    remoteTokenMessenger: findProgramAddress('remote_token_messenger', TOKEN_MESSENGER_MINTER_PROGRAM_ID, [AVAX_DESTINATION_DOMAIN.toString()]).publicKey,
    tokenMinter: findProgramAddress('token_minter', TOKEN_MESSENGER_MINTER_PROGRAM_ID).publicKey,
    localToken: findProgramAddress('local_token', TOKEN_MESSENGER_MINTER_PROGRAM_ID, [USDC_DEV_TOKEN_MINT]).publicKey,
    burnTokenMint: USDC_DEV_TOKEN_MINT,
    messageTransmitterProgram: MESSAGE_TRANSMITTER_PROGRAM_ID,
    tokenMessengerMinterProgram: TOKEN_MESSENGER_MINTER_PROGRAM_ID,
    tokenProgram: TOKEN_PROGRAM_ID,
    eventAuthority: findProgramAddress('__event_authority', TOKEN_MESSENGER_MINTER_PROGRAM_ID).publicKey,
    eventRentPayer: keypair.publicKey,
    messageSentEventData: msgSendEventData.publicKey,
    systemProgram: SystemProgram.programId,
    program: TOKEN_MESSENGER_MINTER_PROGRAM_ID
  }).transaction()
  ```
  
  but a similar call using the Wormhole Bridge "postMessage" instruction fails.  It is even more simpler:
  
  ```
  const postMsgIx = await wormholeProgram.methods.postMessage({
    nonce: 0x1111,
    payload: depositWithPayloadStruct,
    consistencyLevel: 1,  // Finalized
  }).accountsStrict({
    bridge: findProgramAddress('bridge', WORMHOLE_CORE_PROGRAM_ID).publicKey,
    message: messageAccount.publicKey,
    emitter: keypair.publicKey, // Emitter = myself.
    sequence,
    payer: keypair.publicKey,
    feeCollector: findProgramAddress('fee_collector', WORMHOLE_CORE_PROGRAM_ID).publicKey,
    clock: SYSVAR_CLOCK_PUBKEY,
    rent: SYSVAR_RENT_PUBKEY,
    systemProgram: SystemProgram.programId
  }).transaction()
  ```
  
  The error I'm getting is: 
  ```
Error: Invalid arguments: bridge not provided.
    at /home/hernandp/src/xy/app/packages/cctp-support/node_modules/@coral-xyz/anchor/src/program/common.ts:51:8
    at Array.forEach (<anonymous>)
    at validateAccounts (/home/hernandp/src/xy/app/packages/cctp-support/node_modules/@coral-xyz/anchor/src/program/common.ts:46:9)
    at MethodsBuilder.ix [as _ixFn] (/home/hernandp/src/xy/app/packages/cctp-support/node_modules/@coral-xyz/anchor/src/program/namespace/instruction.ts:44:23)
 ```
    
 I printed the arguments before validateAccounts is executed and I get:
 
``` 
[
  { name: 'bridge', isMut: true, isSigner: false },
  { name: 'message', isMut: true, isSigner: true },
  { name: 'emitter', isMut: false, isSigner: true },
  { name: 'sequence', isMut: true, isSigner: false },
  { name: 'payer', isMut: true, isSigner: true },
  { name: 'feeCollector', isMut: true, isSigner: false },
  { name: 'clock', isMut: false, isSigner: false },
  { name: 'rent', isMut: false, isSigner: false },
  { name: 'systemProgram', isMut: false, isSigner: false }
]
```
which are the proper accounts for the postMessage instruction (you can double check this at https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/f28fc6fb5577fa17094860512b48b02ccb4cb8c6/platforms/solana/protocols/core/src/anchor-idl/wormhole.json)

but the account array that is getting used for evaluation is empty, but I provided them in the method builder.

Any tips on this?

Thanks

**Comment by acheroncrypto** [comment]
> which are the proper accounts for the postMessage instruction (you can double check this at https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/f28fc6fb5577fa17094860512b48b02ccb4cb8c6/platforms/solana/protocols/core/src/anchor-idl/wormhole.json)

`postMessage` instruction takes 3 arguments instead of a single object argument:

https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/f28fc6fb5577fa17094860512b48b02ccb4cb8c6/platforms/solana/protocols/core/src/anchor-idl/wormhole.json#L112-L125

You'd pass it as:

```ts
wormholeProgram.methods.postMessage(nonce, payload, consistencyLevel)
```
