### ISSUE TITLE
`anchor.workspace` is empty causing `ReferenceError` during `anchor test`

### ISSUE THREAD

**Issue by deFang** [coral-xyz/anchor#3099]
**Description:**

When running `anchor test`, I encounter a `ReferenceError` because `structuredClone` is not defined. This issue seems to be related to `anchor.workspace` being empty. Here is the full error message:

```
ReferenceError: structuredClone is not defined
    at convertIdlToCamelCase (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/@coral-xyz/anchor/src/idl.ts:337:25)
    at new Program (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/@coral-xyz/anchor/src/program/index.ts:289:48)
    at Object.get (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/@coral-xyz/anchor/src/workspace.ts:74:37)
    at Suite.<anonymous> (/Users/daniel/Codes/ratex/ssd/ratex-test/tests/ratex-test.ts:9:36)
    at Object.create (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/daniel/Codes/ratex/ssd/ratex-test/tests/ratex-test.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module.m._compile (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.exports.requireOrImport (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at Object.exports.loadFilesAsync (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/daniel/Codes/ratex/ssd/ratex-test/node_modules/mocha/lib/cli/run.js:374:5)
```

**Versions:**

- `solana-cli` version: 1.18.18
- `anchor-cli` version: 0.30.1

**Comment by acheroncrypto** [comment]
Answered here https://github.com/coral-xyz/anchor/issues/2969#issuecomment-2110412563
