### ISSUE TITLE
IDL generation with const generics fails

### ISSUE THREAD

**Issue by mgild** [coral-xyz/anchor#632]
Given:

```
#[derive(Clone, Copy, AnchorSerialize, AnchorDeserialize)]
pub struct Array32<T: Sized, const S: usize> {
    data: [T; S],
    len: usize
}
```

Build fails with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:162:78
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <anchor_syn::idl::IdlType as core::str::traits::FromStr>::from_str
   4: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   6: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
   7: anchor_syn::idl::file::parse_ty_defs
   8: anchor_syn::idl::file::parse
   9: anchor_cli::build_cwd
  10: anchor_cli::build
  11: anchor_cli::entry
  12: anchor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is there any current alternative to produce the same effect?

**Comment by mgild** [comment]
Full trace

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:162:78
stack backtrace:
   0:        0x1009d7b53 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0ed5923a649e289
   1:        0x10072441c - core::fmt::write::h723e23f094c14816
   2:        0x1009d5c2a - std::io::Write::write_fmt::h1daf80ef468fdbda
   3:        0x1009d6def - std::panicking::default_hook::{{closure}}::h8051ec46d4673635
   4:        0x1009d603d - std::panicking::default_hook::h00940783d59e1f09
   5:        0x1009d5ad9 - std::panicking::rust_panic_with_hook::he7eacb7ac12236de
   6:        0x1009f4d6a - std::panicking::begin_panic_handler::{{closure}}::h9bb906e7fabe48fb
   7:        0x1009f4cd8 - std::sys_common::backtrace::__rust_end_short_backtrace::hfcf6bfb40d3fb01c
   8:        0x1009f4c80 - _rust_begin_unwind
   9:        0x100bd722f - core::panicking::panic_fmt::h08a838c42de6f998
  10:        0x100bd7515 - core::result::unwrap_failed::he337c4f6dc8df678
  11:        0x1006c1f84 - <anchor_syn::idl::IdlType as core::str::traits::FromStr>::from_str::h116d19c67c54e99f
  12:        0x10067f152 - <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next::h6a9d78f7d3a78c4c
  13:        0x10065a07f - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h17b7eb334a8e3ec5
  14:        0x10067f577 - <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next::h83e57950738718e0
  15:        0x100685ada - anchor_syn::idl::file::parse_ty_defs::hf69364007ebce20f
  16:        0x1005b19cd - anchor_syn::idl::file::parse::hafe939cea8ea545d
  17:        0x1006456b0 - anchor_cli::build_cwd::h809a6e6d9ea06e7d
  18:        0x1005ae21e - anchor_cli::build::h77fa0f39b84d31a1
  19:        0x1005a3964 - anchor_cli::entry::hfef1a5725ae0ee97
  20:        0x1004d74c0 - anchor::main::h5554fc0f5dc81974
  21:        0x1004d520a - std::sys_common::backtrace::__rust_begin_short_backtrace::hf48670100fa3d727
  22:        0x1004d7a17 - _main
```

**Comment by acamill** [comment]
Hit the same error why using `const xx: usize`, a litteral number worked as fix

**Comment by acamill** [comment]
> This issue can also be seen using the following code and anchor-lang = 17.0
> 
> ```rust
> pub const DATA_LEN: usize = 128;
> 
> #[account]
> pub struct DataAccount {
>     pub data: [u8; DATA_LEN],
> }
> ```
> 
> As stated above changing `data` type to `[u8, 128]` fixes the problem

Yep that's what I attempted to say above, clearer 👍

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.

**Comment by acamill** [comment]
Thank you!
