### ISSUE TITLE
Anchor test failing on local devnet

### ISSUE THREAD

**Issue by JIVIN0902** [coral-xyz/anchor#831]
Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

When I run anchor test command its failing due to this error . I don't know what this is.

```
use anchor_lang::prelude::*;

declare_id!("JessifiGcYGSnfFpF6ffPFuGusKVFZUBcfhQDcGd3t2");

#[program]
pub mod mysolanaapp {
    use super::*;
    pub fn initialize(ctx: Context<Create>) -> ProgramResult {
        Ok(())
    }
}
#[derive(Accounts)]
pub struct Create {

}


#[account]
pub struct BaseAccount{
    pub count: u64
}
```

```
const assert = require("assert");
const anchor = require("@project-serum/anchor");
const { SystemProgram } = anchor.web3;

describe("mysolanaapp", () => {
	/* create and set a Provider */
	let _baseAccount;
	const provider = anchor.Provider.env();
	anchor.setProvider(provider);
	const program = anchor.workspace.Mysolanaapp;
	it("Is initialized!", async () => {
		const program = anchor.workspace.Mysolanaapp;
		const tx = await program.rpc.initialize();
		console.log("Your transaction signature", tx);
	});
})

````

**Comment by xjcaa** [comment]
My guess is you don't have lamports in your local wallet, since you don't create any other accounts.

**Comment by JIVIN0902** [comment]
Thnx. That was the issue.

**Comment by JIVIN0902** [comment]
@xjcaa but now if i run anchor test it gives me this error

Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist

**Comment by xjcaa** [comment]
That error appears when you have a local validator running - can you check that's not the case?

**Comment by JIVIN0902** [comment]
@xjcaa I am currently reading an article which requires me to have a local validator running. Does this mean I have to stop it??

**Comment by JIVIN0902** [comment]
If i stop the test validator and run anchor test i get this 
Translating error FetchError: request to http://127.0.0.1:8899/ failed, reason: socket hang up

**Comment by byang223** [comment]
> If i stop the test validator and run anchor test i get this Translating error FetchError: request to http://127.0.0.1:8899/ failed, reason: socket hang up

Having the same issue, did you ever resolve this?

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
I'm having this on:

```
$ anchor --version
anchor-cli 0.18.2
$ git remote get-url origin
git@github.com:someteamone/cross-pile.git
$ 
```

the exception on `anchor test` is:

```
Transaction simulation failed: Attempt to load a program that does not exist 
    
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
    at Connection.sendEncodedTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/connection.ts:3689:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/connection.ts:3649:20)
    at sendAndConfirmRawTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (/home/userone/vcs/cross-pile/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at Object.rpc [as initialize] (/home/userone/vcs/cross-pile/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:24:23) {
  logs: []
}
```

some more versions:

```
$ node --version
v16.11.1
$ npm --version
8.0.0
$ lsb_release -dc && uname -a
Description:	Ubuntu 20.04.3 LTS
Codename:	focal
Linux x 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ 
```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
```
$ ps auxwww|grep validator
userone   116071  0.0  0.0   8160   732 pts/2    S+   05:34   0:00 grep --color=auto validator
$ 
```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
See also: https://github.com/project-serum/anchor/issues/323#issuecomment-1010670982

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
Seems to be missing fixed omitted from the mainline?

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
On `anchor test`, whether I either run a background validator or not, rebuild/redeploy or not, this error gets output.

Re: `cross-pile`.

```
Transaction simulation failed: Attempt to load a program that does not exist 
    
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
    at Connection.sendEncodedTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/connection.ts:3689:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/connection.ts:3649:20)
    at sendAndConfirmRawTransaction (/home/userone/vcs/cross-pile/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (/home/userone/vcs/cross-pile/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at Object.rpc [as initialize] (/home/userone/vcs/cross-pile/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:24:23) {
  logs: []
}
```

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
my issues was due to wrong program id at onchain `.rs`

**Comment by 1Spaceone** [comment]
> my issues were due to wrong program id at onchain `.rs` and some other places
> 
> all fixed for me

hi
Pls tell how fix?

I have such an error:


```
Transaction simulation failed: Attempt to load a program that does not exist

1) Is initialized!


  0 passing (55ms)
  1 failing

  1) myepicproject
       Is initialized!:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:6634:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Connection.sendRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:6593:20)
      at async sendAndConfirmRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:8589:21)
      at async Provider.send (node_modules/@project-serum/anchor/dist/cjs/provider.js:90:22)
      at async Object.rpc [as initialize] (node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:31:31)
      at async Context.<anonymous> (tests/myepicproject.js:11:16)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 1Spaceone** [comment]
Solution - changed in the file lib.rs (/ srs) and Anchor.toml - Program Id

**Comment by jdaviderb** [comment]
this solved the problem 👇 

it seems `anchor test` runs `solana-test-validator` internally  so I just terminated the 'solana-test-validator' process and ran `anchor test` and it worked

**Comment by ratulb** [comment]
Anchor.toml - picks up a wrong program id than that returned from deployed - using:

`solana program deploy`

anchor-cli 0.20.1
v17.4.0

**Comment by Henry-E** [comment]
A lot of different thing going on in this thread, many different issues and errors. Not clear that there's a bug in anchor that directly needs to be fixed.
