### ISSUE TITLE
path undefined in minimal example

### ISSUE THREAD

**Issue by davidspies** [coral-xyz/anchor#872]
When I try to run the minimal example in the tutorial, I get: 

```
node:internal/fs/utils:670
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at Function.local (/home/david/projects/anchor/examples/tutorial/basic-0/node_modules/@project-serum/anchor/dist/cjs/provider.js:154:92)
    at Function.local (/home/david/projects/anchor/examples/tutorial/basic-0/node_modules/@project-serum/anchor/dist/cjs/provider.js:38:35)
    at Object.<anonymous> (/home/david/projects/anchor/examples/tutorial/basic-0/client.js:8:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I _did_ `solana-keygen new` and the path to the wallet defined in `Anchor.toml` is a file which exists:

`wallet = "~/.config/solana/id.json"`

Why is it complaining?

**Comment by saito-kosuke** [comment]
@davidspies 
Could you refer to below for more detail?
https://github.com/project-serum/anchor/pull/832

**Comment by na** [comment]
Ran into the same issue today.  The issue is with https://github.com/project-serum/anchor/blob/cfba251fc4cb366adcd4ad48eefee2201d7448c5/ts/src/provider.ts#L236 which is using readFileSync(process.env.ANCHOR_WALLET) and obviously if ANCHOR_WALLET isn't set it won't work.  #832 provides details for setting ANCHOR_WALLET.
